config/routes.rb
PingPong::Application.routes.draw do
  
  root to: 'users#index'   
  resources :games
  resources :users
  namespace :api, path: 'api', defaults: { format: 'json' } do
    namespace :v1, path: 'v1', defaults: { format: 'json' } do
      resources :login, only: [:create]
      resources :leaderboard, only: [:index]
      resources :games, only: [:create]
    end
  end

end

app/models/game.rb
class Game < ActiveRecord::Base
	after_create :update_scores

	validate :winner_does_not_equal_loser

	private

	def winner_does_not_equal_loser 
		errors.add(:base, "You can't play yourself silly") if self.winner_id == self.loser_id
	end

	def update_scores
		@loser = User.find(self.loser_id)
		@winner = User.find(self.winner_id)
	
		calculate_expected_outcome(@loser, @winner)

		self.winner_score += 10 * @weighted_average
		self.loser_score -= 5 * @weighted_average
		self.save

		Ranking.update_score
		update_rankings
	end

	def calculate_expected_outcome(loser, winner)
		if winner.ranking.ranking < loser.ranking.ranking 
			@expected_winner = winner 
			@expected_loser = loser
			calculate_weighted_average(@expected_loser, @expected_winner, true)
		elsif winner.ranking.ranking > loser.ranking.ranking 
		  @expected_winner = loser
			@expected_loser = winner
			calculate_weighted_average(@expected_loser, @expected_winner, false)
		end
	end

	def calculate_weighted_average(expected_loser, expected_winner, predicted_outcome)
		user_count = User.all.count

		if predicted_outcome == true
			@weighted_average = ((expected_winner.ranking.ranking - expected_loser.ranking.ranking).to_f.abs  / user_count).to_f
			return @weighted_average
		else
			@weighted_average = 1 + ((expected_winner.ranking.ranking - expected_loser.ranking.ranking).to_f.abs / user_count.to_f)
			return @weighted_average
		end
	end

	def update_rankings
		@rankings = Ranking.all
		@rankings.order!("score desc")
		ranking = 1
		@rankings.each do |x|
			x.update(ranking:ranking)
			ranking += 1
		end
	end
end

app/controllers/api/v1/games_controller.rb
class Api::V1::GamesController < ApplicationController
def create
		params[:winner_id] = params[:winner_id].to_i
		params[:loser_id] = params[:loser_id].to_i

    @game = Game.new(winner_id: params[:winner_id], loser_id: params[:loser_id])
    loser = User.find(params[:loser_id])
    winner = User.find(params[:winner_id])
    @game.update(winner_ranking: winner.ranking, loser_ranking: loser.ranking)

    if @game.save
    	success_hash =  { success: 'success', message: 'Congrats, your game was successfully logged!' }
      render json: success_hash
    else
    	failure_hash =  { failure: 'failure', message: 'Oh no. Something happened and this game was not saved!' }
      render json: failure_hash
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
    @users = User.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)
    loser = User.find(game_params[:loser_id])
    winner = User.find(game_params[:winner_id])
    @game.update(winner_ranking: winner.ranking, loser_ranking: loser.ranking)

    respond_to do |format|
      if @game.save
        format.html { redirect_to root_url, notice: 'Game was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to root_url, notice: 'Game was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:winner_id, :loser_id)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :winner_id %><br>
    <%= f.collection_select :winner_id, User.order(:username),:id,:username %>
  </div>
  <div class="field">
    <%= f.label :loser_id %><br>
    <%= f.collection_select :loser_id, User.order(:username),:id,:username %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table>
  <thead>
    <tr>
      <th>Winner</th>
      <th>Loser</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= @users.find(game.winner_id).username %></td>
        <td><%= @users.find(game.loser_id).username %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Winner:</strong>
  <%= @game.winner_id %>
</p>

<p>
  <strong>Loser:</strong>
  <%= @game.loser_id %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>